python multitask_jointTrain.py /root/data/zz/datasets/FGVC/ \
  --dataset 'stanford_cars' 'stanford_dogs' 'oxford_flowers' 'nabirds' 'cub2011' \
  --num-classes_list '196' '120' "102" "555" '200' \
  --simple-aug \
  --model vit_base_patch16_224_in21k \
  --batch-size 64 --epochs 500 \
	--opt adamw  --weight-decay 0.05 \
  --warmup-lr 1e-7 --warmup-epochs 50  \
  --lr 5e-5 --min-lr 1e-8 \
  --drop-path 0 --img-size 224 \
	--model-ema --model-ema-decay 0.99992  \
	--output  output/full \
	--amp  --pretrained  \
  --experiment multi_task \
  --gpu_id 2 \
  --batch-size 64 \
  --output output/multi_task \
  --log-wandb
